/* Criando Login Baseado no Windows */

USE [master]
	CREATE LOGIN [DOMAIN\userTest1] 
	FROM WINDOWS WITH DEFAULT_DATABASE=[BD_JOINS]

/* CRIANDO LOGIN BASEADO NO SQL SERVER AUTENTICATION */

USE [master]
	CREATE LOGIN [userTest2]
	WITH PASSWORD=N'123', DEFAULT_DATABASE=[BD_JOINS]

/* Criando usuário no Database MTA_CURSO Vinculando ao Login userTest2*/

USE [BD_JOINS]
	CREATE USER [userTest2] 
	FOR LOGIN [userTest2] 
	WITH DEFAULT_SCHEMA=[dbo]

/* DANDO PERMISSÃO DE SELECT E INSERT AO USUARIO*/

USE [BD_JOINS]
	GRANT SELECT, INSERT ON [dbo].[CAIXA]
	TO [userTest2]

/* NEGANDO PERMISSÃO DE INSERT AO USUARIO*/

USE [BD_JOINS]
	DENY INSERT ON [dbo].[CAIXA]
	TO [userTest2]