-- SELECIONAR DATABASE ALVO
USE MTA_BACKUP
GO

-- LISTAR BACKUPS DISPONÍVEIS E SUAS INFORMAÇÕES
RESTORE FILELISTONLY
FROM DISK = 'D:\MTA_BACKUP_TSQL.bak'
GO

-- REALIZAR BACKUP
RESTORE DATABASE TSQL_MTA_BACKUP
FROM DISK = N'D:\MTA_BACKUP_TSQL.bak'
WITH
FILE = 1,
MOVE 'MTA_BACKUP' TO 'D:\EXEMPLO\MTA_BACKUP_TSQL.mdf',
MOVE 'MTA_BACKUP_LOG' TO 'D:\EXEMPLO\MTA_BACKUP_TSQL_log.ldf',
STATS = 10
GO